### ISSUE TITLE
After upgrading to 0.4, can not use arm

### ISSUE THREAD

**Issue by jaykelly450** [mirskytech/ansible-role-manager#16]
Getting this error on Debian 8 after upgrading ARM to 0.4 via PIP:

Traceback (most recent call last):
  File "/usr/local/bin/arm", line 2, in <module>
    from arm.main import main
  File "/usr/local/lib/python2.7/dist-packages/arm/main.py", line 2, in <module>
    from routes import RouteException
  File "/usr/local/lib/python2.7/dist-packages/arm/routes/__init__.py", line 3, in <module>
    from arm.util import find_subclasses, get_playbook_root
  File "/usr/local/lib/python2.7/dist-packages/arm/util.py", line 5, in <module>
    from pip.vcs.subversion import Subversion
ImportError: No module named vcs.subversion

Version/Platform info:
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux
Python 2.7.9
pip 18.1 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)

I rolled back to 3.2 to which does not produce this error.

**Comment by trevenen** [comment]
I am also getting this error on Centos 7 install. 

Traceback (most recent call last):
  File "/usr/bin/arm", line 2, in <module>
    from arm.main import main
  File "/usr/lib/python2.7/site-packages/arm/main.py", line 2, in <module>
    from routes import RouteException
  File "/usr/lib/python2.7/site-packages/arm/routes/__init__.py", line 3, in <module>
    from arm.util import find_subclasses, get_playbook_root
  File "/usr/lib/python2.7/site-packages/arm/util.py", line 5, in <module>
    from pip.vcs.subversion import Subversion
ImportError: No module named vcs.subversion

Version/Platform info:
Linux  3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux 
Python 2.7.5
pip 19.0.3 from /usr/lib/python2.7/site-packages/pip (python 2.7)
